apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
 registries.conf: |
  registries:
  - name: Github Container Registry
    prefix: ghcr.io
    api_url: https://ghcr.io
    ping: no
    credentials: pullsecret:argocd/github