apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx
helmCharts:
  - name: ingress-nginx
    includeCRDs: true
    releaseName: ingress-nginx
    version: 4.3.0
    repo: https://kubernetes.github.io/ingress-nginx
    namespace: ingress-nginx

